import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import movieData from "../utils/requests";

const Home = ({ results }) => {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Result results={results} />
    </div>
  );
};

export default Home;

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      movieData[genre]?.url || movieData.Trending.url
    }`
  ).then(res => res.json());

  return {
    props: {
      results: request.results,
    },
  };
};
